apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: pod-config
initializers:
  # the name needs to be fully qualified, i.e., containing at least two "."
  - name: hostaliases.initializer.kubernetes.io
    rules:
      # apiGroups, apiVersion, resources all support wildcard "