
apiVersion: v1
kind: Service
metadata:
  name: hostaliases-injector-webhook-svc
  labels:
    app: hostaliases-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: hostaliases-injector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostaliases-config
data:
  config: |
      - name: dataset
        label: dataset
        hostAliases:
        - ip: "1.2.3.4"
          hostnames:
          - "example.com"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostaliases-injector-webhook-deployment
  labels:
    app: hostaliases-injector
spec:
  replicas: 1