apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    hostaliases-injector: enabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gcs
  name: webhook-dp-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcs
  template:
    metadata:
      labels:
        app: gcs
    spec:
      containers:
      - name: sleep
        image: centos
        a