apiVersion: v1
kind: Service
metadata:
  name: proxy-cache
  labels:
    app: proxy-cache
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: proxy-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-cache
spec:
  selector:
    matchLabels:
      app: proxy-cache
  replicas: 1
